<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Form\Handler\Question;

use MU\YourAnswersModule\Form\Handler\Question\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the question object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
