<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Block;

use MU\YourAnswersModule\Block\Base\AbstractModerationBlock;

/**
 * Moderation block implementation class.
 */
class ModerationBlock extends AbstractModerationBlock
{
    // feel free to extend the moderation block here
}
