services:
    mu_youranswers_module.app_settings:
        class: MU\YourAnswersModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
