services:
    # Twig extension
    mu_youranswers_module.twig_extension:
        class: MU\YourAnswersModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@mu_youranswers_module.entity_display_helper"
            - "@mu_youranswers_module.workflow_helper"
            - "@mu_youranswers_module.listentries_helper"
        public: false
        tags: ['twig.extension']
