services:
    # Custom validators
    mu_youranswers_module.validator.list_entry.validator:
        class: MU\YourAnswersModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_youranswers_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_youranswers_module.validator.list_entry.validator }
