<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Block\Form\Type;

use MU\YourAnswersModule\Block\Form\Type\Base\AbstractItemBlockType;

/**
 * Detail block form type implementation class.
 */
class ItemBlockType extends AbstractItemBlockType
{
    // feel free to extend the detail block form type class here
}
