<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\YourAnswersModule\Entity\AnswerEntity;

/**
 * Event base class for filtering answer processing.
 */
class AbstractFilterAnswerEvent extends Event
{
    /**
     * @var AnswerEntity Reference to treated entity instance.
     */
    protected $answer;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterAnswerEvent constructor.
     *
     * @param AnswerEntity $answer Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(AnswerEntity $answer, array $entityChangeSet = [])
    {
        $this->answer = $answer;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return AnswerEntity
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
