<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\HookSubscriber;

use MU\YourAnswersModule\HookSubscriber\Base\AbstractQuestionFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class QuestionFormAwareHookSubscriber extends AbstractQuestionFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
