<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Form\Type\Finder;

use MU\YourAnswersModule\Form\Type\Finder\Base\AbstractAnswerFinderType;

/**
 * Answer finder form type implementation class.
 */
class AnswerFinderType extends AbstractAnswerFinderType
{
    // feel free to extend the base form type class here
}
