<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\ContentType;

use MU\YourAnswersModule\ContentType\Base\AbstractItemType;

/**
 * Generic single item display content type implementation class.
 */
class ItemType extends AbstractItemType
{
    // feel free to extend the content type here
}
