<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Event;

use MU\YourAnswersModule\Event\Base\AbstractFilterQuestionEvent;

/**
 * Event implementation class for filtering question processing.
 */
class FilterQuestionEvent extends AbstractFilterQuestionEvent
{
    // feel free to extend the event class here
}
