<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\DependencyInjection;

use MU\YourAnswersModule\DependencyInjection\Base\AbstractMUYourAnswersExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUYourAnswersExtension extends AbstractMUYourAnswersExtension
{
    // custom enhancements can go here
}
