<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule;

use MU\YourAnswersModule\Base\AbstractAppSettings;

/**
 * Application settings class for handling module variables.
 */
class AppSettings extends AbstractAppSettings
{
    // feel free to add your own methods here
}
