<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Base;

use MU\YourAnswersModule\Listener\EntityLifecycleListener;

/**
 * Events definition base class.
 */
abstract class AbstractYourAnswersEvents
{
    /**
     * The muyouranswersmodule.itemactionsmenu_pre_configure event is thrown before the item actions
     * menu is built in the menu builder.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\ConfigureItemActionsMenuEvent instance.
     *
     * @see MU\YourAnswersModule\Menu\MenuBuilder::createItemActionsMenu()
     * @var string
     */
    const MENU_ITEMACTIONS_PRE_CONFIGURE = 'muyouranswersmodule.itemactionsmenu_pre_configure';
    
    /**
     * The muyouranswersmodule.itemactionsmenu_post_configure event is thrown after the item actions
     * menu has been built in the menu builder.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\ConfigureItemActionsMenuEvent instance.
     *
     * @see MU\YourAnswersModule\Menu\MenuBuilder::createItemActionsMenu()
     * @var string
     */
    const MENU_ITEMACTIONS_POST_CONFIGURE = 'muyouranswersmodule.itemactionsmenu_post_configure';
    /**
     * The muyouranswersmodule.answer_post_load event is thrown when answers
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::postLoad()
     * @var string
     */
    const ANSWER_POST_LOAD = 'muyouranswersmodule.answer_post_load';
    
    /**
     * The muyouranswersmodule.answer_pre_persist event is thrown before a new answer
     * is created in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::prePersist()
     * @var string
     */
    const ANSWER_PRE_PERSIST = 'muyouranswersmodule.answer_pre_persist';
    
    /**
     * The muyouranswersmodule.answer_post_persist event is thrown after a new answer
     * has been created in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::postPersist()
     * @var string
     */
    const ANSWER_POST_PERSIST = 'muyouranswersmodule.answer_post_persist';
    
    /**
     * The muyouranswersmodule.answer_pre_remove event is thrown before an existing answer
     * is removed from the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::preRemove()
     * @var string
     */
    const ANSWER_PRE_REMOVE = 'muyouranswersmodule.answer_pre_remove';
    
    /**
     * The muyouranswersmodule.answer_post_remove event is thrown after an existing answer
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::postRemove()
     * @var string
     */
    const ANSWER_POST_REMOVE = 'muyouranswersmodule.answer_post_remove';
    
    /**
     * The muyouranswersmodule.answer_pre_update event is thrown before an existing answer
     * is updated in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::preUpdate()
     * @var string
     */
    const ANSWER_PRE_UPDATE = 'muyouranswersmodule.answer_pre_update';
    
    /**
     * The muyouranswersmodule.answer_post_update event is thrown after an existing new answer
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterAnswerEvent instance.
     *
     * @see EntityLifecycleListener::postUpdate()
     * @var string
     */
    const ANSWER_POST_UPDATE = 'muyouranswersmodule.answer_post_update';
    
    /**
     * The muyouranswersmodule.question_post_load event is thrown when questions
     * are loaded from the database.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::postLoad()
     * @var string
     */
    const QUESTION_POST_LOAD = 'muyouranswersmodule.question_post_load';
    
    /**
     * The muyouranswersmodule.question_pre_persist event is thrown before a new question
     * is created in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::prePersist()
     * @var string
     */
    const QUESTION_PRE_PERSIST = 'muyouranswersmodule.question_pre_persist';
    
    /**
     * The muyouranswersmodule.question_post_persist event is thrown after a new question
     * has been created in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::postPersist()
     * @var string
     */
    const QUESTION_POST_PERSIST = 'muyouranswersmodule.question_post_persist';
    
    /**
     * The muyouranswersmodule.question_pre_remove event is thrown before an existing question
     * is removed from the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::preRemove()
     * @var string
     */
    const QUESTION_PRE_REMOVE = 'muyouranswersmodule.question_pre_remove';
    
    /**
     * The muyouranswersmodule.question_post_remove event is thrown after an existing question
     * has been removed from the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::postRemove()
     * @var string
     */
    const QUESTION_POST_REMOVE = 'muyouranswersmodule.question_post_remove';
    
    /**
     * The muyouranswersmodule.question_pre_update event is thrown before an existing question
     * is updated in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::preUpdate()
     * @var string
     */
    const QUESTION_PRE_UPDATE = 'muyouranswersmodule.question_pre_update';
    
    /**
     * The muyouranswersmodule.question_post_update event is thrown after an existing new question
     * has been updated in the system.
     *
     * The event listener receives an
     * MU\YourAnswersModule\Event\FilterQuestionEvent instance.
     *
     * @see EntityLifecycleListener::postUpdate()
     * @var string
     */
    const QUESTION_POST_UPDATE = 'muyouranswersmodule.question_post_update';
    
}
