<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Container;

use MU\YourAnswersModule\Container\Base\AbstractLinkContainer;

use Symfony\Component\Routing\RouterInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\Core\Doctrine\EntityAccess;
use Zikula\Core\LinkContainer\LinkContainerInterface;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;

/**
 * This is the link container service implementation class.
 */
class LinkContainer extends AbstractLinkContainer
{
    /**
     * Returns available header links.
     *
     * @param string $type The type to collect links for
     *
     * @return array List of header links
     */
    public function getLinks($type = LinkContainerInterface::TYPE_ADMIN)
    {
        $contextArgs = ['api' => 'linkContainer', 'action' => 'getLinks'];
        $allowedObjectTypes = $this->controllerHelper->getObjectTypes('api', $contextArgs);
        
        $permLevel = LinkContainerInterface::TYPE_ADMIN == $type ? ACCESS_ADMIN : ACCESS_READ;
        
        // Create an array of links to return
        $links = [];
        
        if (LinkContainerInterface::TYPE_ACCOUNT == $type) {
            if (!$this->permissionHelper->hasPermission(ACCESS_OVERVIEW)) {
                return $links;
            }
            
            if (true === $this->variableApi->get('MUYourAnswersModule', 'linkOwnAnswersOnAccountPage', true)) {
                $objectType = 'answer';
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('muyouranswersmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My answers', 'muyouranswersmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }
            
            if (true === $this->variableApi->get('MUYourAnswersModule', 'linkOwnQuestionsOnAccountPage', true)) {
                $objectType = 'question';
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_READ)) {
                    $links[] = [
                        'url' => $this->router->generate('muyouranswersmodule_' . strtolower($objectType) . '_view', ['own' => 1]),
                        'text' => $this->__('My questions', 'muyouranswersmodule'),
                        'icon' => 'list-alt'
                    ];
                }
            }
            
            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('muyouranswersmodule_question_adminindex'),
                    'text' => $this->__('Your answers Backend', 'muyouranswersmodule'),
                    'icon' => 'wrench'
                ];
            }
            
            
            return $links;
        }
        
        $routeArea = LinkContainerInterface::TYPE_ADMIN == $type ? 'admin' : '';
        if (LinkContainerInterface::TYPE_ADMIN == $type) {
            if ($this->permissionHelper->hasPermission(ACCESS_READ)) {
                $links[] = [
                    'url' => $this->router->generate('muyouranswersmodule_question_index'),
                    'text' => $this->__('Frontend', 'muyouranswersmodule'),
                    'title' => $this->__('Switch to user area.', 'muyouranswersmodule'),
                    'icon' => 'home'
                ];
            }
        } else {
            if ($this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                $links[] = [
                    'url' => $this->router->generate('muyouranswersmodule_question_adminindex'),
                    'text' => $this->__('Backend', 'muyouranswersmodule'),
                    'title' => $this->__('Switch to administration area.', 'muyouranswersmodule'),
                    'icon' => 'wrench'
                ];
            }
        }
        
        if (in_array('answer', $allowedObjectTypes)
            && $this->permissionHelper->hasComponentPermission('answer', $permLevel) && $routeArea == 'admin') {
                $links[] = [
                    'url' => $this->router->generate('muyouranswersmodule_answer_' . $routeArea . 'view'),
                    'text' => $this->__('Answers', 'muyouranswersmodule'),
                    'title' => $this->__('Answers list', 'muyouranswersmodule')
                ];
            }
            if (in_array('question', $allowedObjectTypes)
                && $this->permissionHelper->hasComponentPermission('question', $permLevel)) {
                    $links[] = [
                        'url' => $this->router->generate('muyouranswersmodule_question_' . $routeArea . 'view'),
                        'text' => $this->__('Questions', 'muyouranswersmodule'),
                        'title' => $this->__('Questions list', 'muyouranswersmodule')
                    ];
                }
                if ($routeArea == 'admin' && $this->permissionHelper->hasPermission(ACCESS_ADMIN)) {
                    $links[] = [
                        'url' => $this->router->generate('muyouranswersmodule_config_config'),
                        'text' => $this->__('Settings', 'muyouranswersmodule'),
                        'title' => $this->__('Manage settings for this application', 'muyouranswersmodule'),
                        'icon' => 'wrench'
                    ];
                }
                
                return $links;
    }
    // feel free to add own extensions here
}
