<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Entity\Factory\Base;

use Symfony\Component\HttpFoundation\RequestStack;
use MU\YourAnswersModule\Entity\AnswerEntity;
use MU\YourAnswersModule\Entity\QuestionEntity;
use MU\YourAnswersModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var RequestStack
     */
    protected $requestStack;

    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    /**
     * EntityInitialiser constructor.
     *
     * @param RequestStack $requestStack RequestStack service instance
     * @param PermissionHelper $permissionHelper PermissionHelper service instance
     */
    public function __construct(
        RequestStack $requestStack,
        PermissionHelper $permissionHelper
    ) {
        $this->requestStack = $requestStack;
        $this->permissionHelper = $permissionHelper;
    }

    /**
     * Initialises a given answer instance.
     *
     * @param AnswerEntity $entity The newly created entity instance
     *
     * @return AnswerEntity The updated entity instance
     */
    public function initAnswer(AnswerEntity $entity)
    {
        return $entity;
    }

    /**
     * Initialises a given question instance.
     *
     * @param QuestionEntity $entity The newly created entity instance
     *
     * @return QuestionEntity The updated entity instance
     */
    public function initQuestion(QuestionEntity $entity)
    {
        $entity->setForLanguage($this->requestStack->getCurrentRequest()->getLocale());

        return $entity;
    }

}
