<?php
/**
 * YourAnswers.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace MU\YourAnswersModule\Form\EventListener;

use MU\YourAnswersModule\Form\EventListener\Base\AbstractTranslationListener;

/**
 * Translation listener implementation class.
 */
class TranslationListener extends AbstractTranslationListener
{
    // feel free to add your customisation here
}
